package AirLineCorba;


/**
* AirLineCorba/AirLineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Airline.idl
* Thursday, December 22, 2022 12:35:23 PM CET
*/

public interface AirLineOperations 
{
  AirLineCorba.Connect Login (String email, String password);
  AirLineCorba.Connect Signup (String firstName, String lastName, String email, String password, String address, int phoneNumber);
  boolean addVol (String airport, String destination, String takeDate, double totalTicktite, double price);
  boolean removeVol (int volId);
  boolean updateVol ();
  AirLineCorba.Vol getVol (int volId);
  AirLineCorba.Vol[] getVols ();
  AirLineCorba.Vol getVolByDestination (String destination);
  AirLineCorba.Client getClient (String email);
  AirLineCorba.Client[] getClients ();
  boolean Transaction (String email, int ccp, double price);
  boolean addBooking (int clientId, int volId, int ccp, String email);
  AirLineCorba.Booking[] listBookings (int clientId);
} // interface AirLineOperations
