package AirLineCorba;

/**
* AirLineCorba/BookingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Airline.idl
* Thursday, December 22, 2022 12:35:23 PM CET
*/

public final class BookingHolder implements org.omg.CORBA.portable.Streamable
{
  public AirLineCorba.Booking value = null;

  public BookingHolder ()
  {
  }

  public BookingHolder (AirLineCorba.Booking initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AirLineCorba.BookingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AirLineCorba.BookingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AirLineCorba.BookingHelper.type ();
  }

}
