package AirLineCorba;


/**
* AirLineCorba/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Airline.idl
* Thursday, December 22, 2022 12:35:23 PM CET
*/

public final class Client implements org.omg.CORBA.portable.IDLEntity
{
  public int clientId = (int)0;
  public String firstName = null;
  public String lastName = null;
  public String email = null;
  public String address = null;
  public int phoneNumber = (int)0;
  public String password = null;
  public String role = null;
  public int volId = (int)0;

  public Client ()
  {
  } // ctor

  public Client (int _clientId, String _firstName, String _lastName, String _email, String _address, int _phoneNumber, String _password, String _role, int _volId)
  {
    clientId = _clientId;
    firstName = _firstName;
    lastName = _lastName;
    email = _email;
    address = _address;
    phoneNumber = _phoneNumber;
    password = _password;
    role = _role;
    volId = _volId;
  } // ctor

} // class Client
