package AirLineCorba;


/**
* AirLineCorba/Connect.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Airline.idl
* Thursday, December 22, 2022 12:35:23 PM CET
*/

public final class Connect implements org.omg.CORBA.portable.IDLEntity
{
  public boolean status = false;
  public String clientId = null;
  public String role = null;

  public Connect ()
  {
  } // ctor

  public Connect (boolean _status, String _clientId, String _role)
  {
    status = _status;
    clientId = _clientId;
    role = _role;
  } // ctor

} // class Connect
