package AirLineCorba;


/**
* AirLineCorba/Booking.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Airline.idl
* Thursday, December 22, 2022 12:33:39 PM CET
*/

public final class Booking implements org.omg.CORBA.portable.IDLEntity
{
  public int bookingId = (int)0;
  public int volId = (int)0;
  public int clientId = (int)0;
  public String firstName = null;
  public String lastName = null;
  public String airport = null;
  public String destination = null;
  public String takeDate = null;
  public double totalTicktite = (double)0;
  public String bookingDate = null;
  public double price = (double)0;
  public int ccp = (int)0;

  public Booking ()
  {
  } // ctor

  public Booking (int _bookingId, int _volId, int _clientId, String _firstName, String _lastName, String _airport, String _destination, String _takeDate, double _totalTicktite, String _bookingDate, double _price, int _ccp)
  {
    bookingId = _bookingId;
    volId = _volId;
    clientId = _clientId;
    firstName = _firstName;
    lastName = _lastName;
    airport = _airport;
    destination = _destination;
    takeDate = _takeDate;
    totalTicktite = _totalTicktite;
    bookingDate = _bookingDate;
    price = _price;
    ccp = _ccp;
  } // ctor

} // class Booking
